### ISSUE TITLE
Random Colour Generator

### ISSUE THREAD

**Issue by Gaurika-Gupta** [dharmanshu9930/Website#242]
Make a Random Colour Generator website which shows different colour shades eaach time the website is refreshed. Design the project using HTML, CSS, JavaScript.
Try to make the website Responsive.

**Comment by Gaurika-Gupta** [comment]
Please assign me this Project under Hacktoberfest 2022. I would like to work with the above technologies

**Comment by laveshverma007** [comment]
May i work on this, please assign this issue to me

**Comment by Anim3shSinha** [comment]
I would like to work on this issue, please assign it to me.

**Comment by Anim3shSinha** [comment]
@Gaurika-Gupta I have filed the PR at #251
